# Generated by Django 5.2.5 on 2025-09-18 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_studentclass_teacher_timetable_student_class_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'permissions': [('manage_subject', 'Can manage subject')]},
        ),
    ]
