# Generated by Django 5.2.5 on 2025-09-18 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'permissions': [('manage_attendance', 'Can manage attendance')]},
        ),
    ]
